import io
import json
import zipfile
from datetime import datetime, timezone


class TemplateExporter:
    async def export_package(
        self,
        images: list[bytes],
        caption: str,
        hashtags: list[str],
        post_name: str,
        aspect_ratio: str = "1:1",
    ) -> bytes:
        """Package images + caption + metadata into a ZIP archive."""
        buf = io.BytesIO()

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            for i, img_bytes in enumerate(images, 1):
                zf.writestr(f"slides/slide_{i:02d}.jpg", img_bytes)

            caption_text = (
                f"{caption}\n\n"
                f"---\nHASHTAGS:\n{' '.join(hashtags)}\n\n"
                f"---\nGenerated by InstaContentEngine\n"
                f"Post name: {post_name}\n"
                f"Slides: {len(images)}\n"
            )
            zf.writestr("caption.txt", caption_text)

            metadata = {
                "post_name": post_name,
                "caption": caption,
                "hashtags": hashtags,
                "num_slides": len(images),
                "aspect_ratio": aspect_ratio,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            }
            zf.writestr("metadata.json", json.dumps(metadata, indent=2))

        buf.seek(0)
        return buf.getvalue()
