"""baseline schema

Revision ID: 324f6331829b
Revises:
Create Date: 2026-07-19 12:04:13.825965
"""
from alembic import op
import sqlalchemy as sa


revision = '324f6331829b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('heading_font_path', sa.Text(), nullable=True),
    sa.Column('body_font_path', sa.Text(), nullable=True),
    sa.Column('logo_position', sa.String(length=20), nullable=True),
    sa.Column('logo_scale', sa.Float(), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=True),
    sa.Column('template_style', sa.String(length=20), nullable=True),
    sa.Column('niche_box_color', sa.String(length=7), nullable=True),
    sa.Column('niche_box_palette', sa.JSON(), nullable=True),
    sa.Column('description_box_alpha', sa.Float(), nullable=True),
    sa.Column('show_logo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canva_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instagram_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('seo_keywords', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('hook', sa.Text(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('template_style', sa.String(length=20), nullable=True),
    sa.Column('text_model', sa.String(length=100), nullable=True),
    sa.Column('image_model', sa.String(length=100), nullable=True),
    sa.Column('brand_engine', sa.String(length=20), nullable=True),
    sa.Column('instagram_media_id', sa.String(length=100), nullable=True),
    sa.Column('published_url', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_image_urls', sa.JSON(), nullable=True),
    sa.Column('schedule_error', sa.Text(), nullable=True),
    sa.Column('pillar', sa.String(length=30), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_user_id'), ['user_id'], unique=False)

    op.create_table('user_credentials',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('openrouter_api_key_enc', sa.Text(), nullable=True),
    sa.Column('instagram_access_token_enc', sa.Text(), nullable=True),
    sa.Column('instagram_user_id_enc', sa.Text(), nullable=True),
    sa.Column('imgbb_api_key_enc', sa.Text(), nullable=True),
    sa.Column('x_api_key_enc', sa.Text(), nullable=True),
    sa.Column('x_api_secret_enc', sa.Text(), nullable=True),
    sa.Column('x_access_token_enc', sa.Text(), nullable=True),
    sa.Column('x_access_token_secret_enc', sa.Text(), nullable=True),
    sa.Column('unsplash_access_key_enc', sa.Text(), nullable=True),
    sa.Column('pexels_api_key_enc', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('post_insights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('saved', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('video_views', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_insights_post_id'), ['post_id'], unique=False)

    op.create_table('slides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('image_source', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('gen_prompt', sa.Text(), nullable=True),
    sa.Column('attribution', sa.JSON(), nullable=True),
    sa.Column('render_params', sa.JSON(), nullable=True),
    sa.Column('raw_image_path', sa.Text(), nullable=True),
    sa.Column('original_overlay_text', sa.Text(), nullable=True),
    sa.Column('original_niche_text', sa.Text(), nullable=True),
    sa.Column('gen_model', sa.String(length=100), nullable=True),
    sa.Column('canva_template_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    with op.batch_alter_table('post_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_insights_post_id'))

    op.drop_table('post_insights')
    op.drop_table('user_credentials')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_user_id'))

    op.drop_table('posts')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('instagram_tokens')
    op.drop_table('canva_tokens')
    op.drop_table('brand_configs')
    # ### end Alembic commands ###
