"""add brand voice to users

Revision ID: f4ab42df24eb
Revises: 324f6331829b
Create Date: 2026-07-19 16:00:45.957272
"""
from alembic import op
import sqlalchemy as sa


revision = 'f4ab42df24eb'
down_revision = '324f6331829b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_voice_preset', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('brand_voice_custom', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('brand_voice_custom')
        batch_op.drop_column('brand_voice_preset')

    # ### end Alembic commands ###
